name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: linear1
      id: linear1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: linear1
        setup-command: ''
        command: gradle test --tests "*linear1*"
        timeout: 10
        max-score: 1
    - name: recursivelinear
      id: recursivelinear
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: recursivelinear
        setup-command: ''
        command: gradle test --tests "*recursivelinear*"
        timeout: 10
        max-score: 1
    - name: binarySearch
      id: binarysearch
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: binarySearch
        setup-command: ''
        command: gradle test --tests "*binarySearch*"
        timeout: 10
        max-score: 1
    - name: recursiveBinary
      id: recursivebinary
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: recursiveBinary
        setup-command: ''
        command: gradle test --tests "*recursiveBinary*"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LINEAR1_RESULTS: "${{steps.linear1.outputs.result}}"
        RECURSIVELINEAR_RESULTS: "${{steps.recursivelinear.outputs.result}}"
        BINARYSEARCH_RESULTS: "${{steps.binarysearch.outputs.result}}"
        RECURSIVEBINARY_RESULTS: "${{steps.recursivebinary.outputs.result}}"
      with:
        runners: linear1,recursivelinear,binarysearch,recursivebinary
